= SUSE Enterprise Storage Documentation

Documentation for the SUSE Enterprise Storage Product

Released versions of the documentation are published at
https://documentation.suse.com/#ses.


== Branches

.Overview of important branches
[options="header"]
|================================================
| Name            | Purpose
| `master`        | development for SES 7
| `maintenance/ses6`| stable for SES 6
| `maintenance/ses5`| stable for SES 5.5
|================================================


== Contributing

If you would like to contribute, please fork this repository and send
pull requests. Always use the `master` branch for your edits!

== Writing DocBook

To contribute to the documentation, you need to write DocBook.

* You can learn about DocBook syntax at http://docbook.org/tdg5/en/html .
* SUSE documents are generally built with DAPS (package `daps`) and the
  SUSE XSL Stylesheets (package `suse-xsl-stylesheets`). Ideally, you should
  get these from the repository `Documentation:Tools`. However, slightly
  older versions are also available from the SLE and openSUSE repositories.
* Basic daps usage:
** `$ daps -d DC-<YOUR_BOOK> validate`: Make sure what you have written is
    well-formed XML and valid DocBook 5
** `$ daps -d DC-<YOUR_BOOK> pdf`: Build a PDF
** `$ daps -d DC-<YOUR_BOOK> html`: Build a HTML
** Learn more at https://opensuse.github.io/daps
