= SUSE Enterprise Storage Documentation

Documentation for the SUSE Enterprise Storage Product

Released versions of the documentation are published at
https://documentation.suse.com/#ses.


== Branches

.Overview of important branches
[options="header"]
|================================================
| Name              | Purpose
| `main`            | development for SES 7
| `maintenance/ses6`| stable for SES 6
| `maintenance/ses5`| stable for SES 5.5
|================================================

***On Feb 20, 2021, we switched to a new default branch.***
***The default branch is now called `main`.***

* *Use the main branch* as the basis of your commits/of new feature branches.


=== How to update your local repository

If you *created* a local clone or GitHub fork of this repo *before Feb 20, 2021, do the following*:

[code]
====
git branch -m master main
git fetch origin
git branch -u origin/main main
git pull -r
====

== Contributing

Thank you for contributing to this repo. When creating a pull request, please follow the guidelines below:

. If you want to contribute to the most recent release, create your pull request against the `main` branch. The `main` branch is protected.

. If you want to contribute to a previous release, please create your pull request against the respective `maintenance/*` branch. These branches are also protected.

. Make sure all validation (Travis CI) checks are passed.

. For your pull request to be reviewed, please tag the relevant subject matter expert(s) from the development team (if applicable) and members of the documentation team.

. Implement the required changes. If you have any questions, ping a documentation team member in #susedoc on RocketChat.

. For help on style and structure, refer to the https://documentation.suse.com/style/current[Documentation Style Guide].


== Editing DocBook

To contribute to the documentation, you need to write DocBook.

* You can learn about DocBook syntax at http://docbook.org/tdg5/en/html .
* SUSE documents are generally built with DAPS (package `daps`) and the
  SUSE XSL Stylesheets (package `suse-xsl-stylesheets`).

*  Install the documentation environment with the following command:
+
[source]
----
sudo /sbin/OneClickInstallUI https://gitlab.nue.suse.com/susedoc/doc-ymp/raw/master/Documentation.ymp
----

* Basic DAPS usage:
** `$ daps -d DC-<YOUR_BOOK> validate`: Make sure what you have written is
    well-formed XML and valid DocBook 5
** `$ daps -d DC-<YOUR_BOOK> pdf`: Build a PDF document
** `$ daps -d DC-<YOUR_BOOK> html`: Build multi-page HTML document
** `$ daps -d DC-<YOUR_BOOK> optipng`: Always optimize new PNG images
** Learn more at https://opensuse.github.io/daps
* To contribute from a non-SUSE distribution, you can use the provided
  Dockerfile/docker-compose.yml files.
* Using DAPS from Docker is similarly easy:
** `$ docker-compose run daps -d DC-<YOUR_BOOK> validate`: Make sure what you have written is
    well-formed XML and valid DocBook 5
** `$ docker-compose run daps -d DC-<YOUR_BOOK> pdf`: Build a PDF document
** `$ docker-compose run daps -d DC-<YOUR_BOOK> html`: Build multi-page HTML document
