#!/bin/sh
#
# To install this file, you need to create a symbolic link inside your
# .git/hooks directory:
# $ cd .git/hooks && ln -s ../../hooks/pre-commit pre-commit
#
#
# Run xmlformat for XML files being commited

# Extend the variable to search for more config files:
CONFIG_FILES="~/.config/daps/docbook-xmlformat.conf /etc/daps/docbook-xmlformat.conf"
# The found config file:
CONFIG=""
for cfg in $CONFIG_FILES; do
  if [ -r "$cfg" ]; then
     CONFIG="$cfg"
     break
  fi
done

if [ -z "$CONFIG" ]; then
    echo "ERROR: File 'docbook-xmlformat.conf' not found" >/dev/stderr
    exit 10
fi

XML_FORMAT_EXECS="/usr/bin/xmlformat //usr/bin/xmlformat.rb usr/bin/xmlformat.pl"
XML_FORMAT=""
for script in $XML_FORMAT_EXECS; do
   if [ -x "$script" ]; then
       XML_FORMAT="$script"
       break
   fi
done

if [ -z "$XML_FORMAT" ]; then
    echo "ERROR: 'xmlformat' command not found" >/dev/stderr
￼    exit 10
fi

# get list of 'A'dded and 'M'odified XML files
XML_FILES=$(git status --porcelain xml/*.xml | awk 'match($1, "M|A") {print $2}' | tr '\n' ' ')

# run xmlformat on ech of them
for FILE in $XML_FILES; do
    echo "XML-formatting file: $FILE"
    XML_FORMAT_OUTPUT="$($XML_FORMAT -i -f $XML_FORMAT_CFG $FILE 2>&1)"
    if [ -n $XML_FORMAT_OUTPUT ]; then
        echo "XML format successful"
    else
        echo "ERROR: Syntax error in file $FILE" >/dev/stderr
        exit 10
    fi
done
