#!/bin/sh
#
# To install this file, you need to create a symbolic link inside your
# .git/hooks directory:
# $ cd .git/hooks && ln -s ../../hooks/pre-commit pre-commit
#
#
# Run xmlformat for XML files being commited

# look for the `docbook-xmlformat.conf` file
if [ -r ~/.config/daps/docbook-xmlformat.conf ]; then
    XML_FORMAT_CFG='~/.config/daps/docbook-xmlformat.conf'
elif [ -r /etc/daps/docbook-xmlformat.conf ]; then
    XML_FORMAT_CFG='/etc/daps/docbook-xmlformat.conf'
else
    echo "ERROR: File 'docbook-xmlformat.conf' not found" >/dev/stderr
    exit 10
fi

# look for the xmlformat binary
if [ -x /usr/bin/xmlformat ]; then
    XML_FORMAT='/usr/bin/xmlformat'
elif [ -x /usr/bin/xmlformat.pl ]; then
    XML_FORMAT='/usr/bin/xmlformat.pl'
else
    echo "ERROR: 'xmlformat' command not found" >/dev/stderr
    exit 10
fi

# get list of 'A'dded and 'M'odified XML files
XML_FILES=$(git status --porcelain | awk 'match($1, "M|A") {print $2}' | grep ".xml$" | tr '\n' ' ')

# run xmlformat on ech of them
for FILE in $XML_FILES; do
    echo "XML-formatting file: $FILE"
    XML_FORMAT_OUTPUT="$($XML_FORMAT -i -f $XML_FORMAT_CFG $FILE 2>&1)"
    if [ -n $XML_FORMAT_OUTPUT ]; then
        echo "XML format successful"
    else
        echo "ERROR: Syntax error in file $FILE" >/dev/stderr
        exit 10
    fi
done
