#!/bin/sh
#
# To install this file, you need to create a symbolic link inside your
# .git/hooks directory such as:
# $ cd .git/hooks && ln -s ../../hooks/pre-commit pre-commit
#
# To specify custom xmlformat  config file,
# export the XML_FORMAT_CFG environment variable
#
# To specify custom xmlformat binary,
# export the XML_FORMAT environment variable
#
#
# Run xmlformat for XML files being commited

# Extend the variable to search for more config files:
XML_FORMAT_CFGS="$XML_FORMAT_CFG ~/.config/daps/docbook-xmlformat.conf /etc/daps/docbook-xmlformat.conf"
# The found config file:
XML_FORMAT_CFG=""
for cfg in $XML_FORMAT_CFGS; do
    if [ -r "$cfg" ]; then
        XML_FORMAT_CFG="$cfg"
        break
    fi
done

if [ -z "$XML_FORMAT_CFG" ]; then
    echo "ERROR: File 'docbook-xmlformat.conf' not found" >/dev/stderr
    exit 10
fi

XML_FORMAT_EXECS="$XML_FORMAT /usr/bin/xmlformat /usr/bin/xmlformat.rb /usr/bin/xmlformat.pl"
XML_FORMAT=""
for script in $XML_FORMAT_EXECS; do
    if [ -x "$script" ]; then
        XML_FORMAT="$script"
        break
    fi
done

if [ -z "$XML_FORMAT" ]; then
    echo "ERROR: 'xmlformat' command not found" >/dev/stderr
    exit 10
fi

# get list of 'A'dded and 'M'odified XML files
XML_FILES=$(git status --porcelain xml/*.xml | awk 'match($1, "M|A") {print $2}' | tr '\n' ' ')

# run xmlformat on ech of them
for file in $XML_FILES; do
    XML_FORMAT_OUTPUT="$($XML_FORMAT -i -f $XML_FORMAT_CFG $file 2>&1)"
    if [ -n "$XML_FORMAT_OUTPUT" ]; then
        echo "ERROR: Syntax error in file $file" >/dev/stderr
        exit 10
    fi
done
