# Add .github/workflows/reformat-xml.yml
---
name: Reformat XML

on:
  push:
    paths:
      - "xml/*.xml"
      - "*.xml"

jobs:
  reformat-xml:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
           # Number of commits to fetch. See above.
           fetch-depth: 0

      - name: Format XML
        id: dbxml
        uses: tomschr/xml-format-action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          config: https://github.com/openSUSE/daps/raw/main/etc/docbook-xmlformat.conf

      - name: Push
        if: ${{ steps.dbxml.outputs.xmlfound }}
        run: |
            # Remove any refs/heads/ parts:
            BRANCH="${GITHUB_REF#refs/heads/}"
            URL="https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git"
            git push "$URL" "$BRANCH"

